---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CompMod

<!-- badges: start -->
<!-- badges: end -->

CompMod is an R package for comparable company analysis (comps). It helps with reading valuation data from Excel, computing trading multiples, and summarizing peer group statistics.

## Installation

```r
# install.packages("devtools")
devtools::install_github("ADC-405-S26/CompMod")
```

## Examples

```{r setup}
library(CompMod)
```

#### Read a valuation Excel file

```{r}
tmp <- tempfile(fileext = ".xlsx")
writexl::write_xlsx(valuation_data, tmp)
df <- read_valuation_excel(tmp)
head(df)
```

#### Compute trading multiples

```{r}
comps <- calc_multiples(valuation_data)
comps[, c("Company.Name", "EV.Revenue", "EV.EBITDA", "P.E")]
```

#### Summarise the peer group

```{r}
peer_summary(comps)
```



#### Read a valuation Excel file

```{r}
# install.packages("writexl")
tmp <- tempfile(fileext = ".xlsx")
writexl::write_xlsx(valuation_data, tmp)
df <- read_valuation_excel(tmp)
head(df)
```

